# Generated by Django 4.1.4 on 2023-01-04 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=210)),
                ("image", models.TextField(default="")),
                ("roles", models.TextField(default="USER_ROLE")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Crystal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField(default="")),
                ("vibration", models.IntegerField(default=0)),
                ("benefits", models.TextField(default="")),
                ("properties", models.TextField(default="")),
                ("zodiac", models.TextField(default="")),
                ("planets", models.TextField(default="")),
                ("elements", models.TextField(default="")),
                ("chakras", models.TextField(default="")),
                ("image_crystal", models.TextField(default="")),
                ("image_gemstone", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="CrystalStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                ("price", models.BigIntegerField(default=0)),
                ("state", models.BooleanField(default=True)),
                (
                    "id_crystal",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plants.crystal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_products", models.IntegerField()),
                ("total_cost", models.BigIntegerField()),
                ("order_at", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrderSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_products", models.IntegerField()),
                ("address", models.TextField()),
                ("payment_method", models.TextField()),
                ("payment_state", models.BooleanField()),
                ("order_at", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=210)),
                ("other_names", models.TextField(default="")),
                ("description", models.TextField(default="")),
                ("species", models.CharField(default="Other", max_length=200)),
                ("group", models.CharField(default="Succulent", max_length=200)),
                ("light", models.TextField(default="")),
                ("irrigation", models.CharField(default="", max_length=200)),
                ("temperature", models.CharField(default="", max_length=200)),
                ("precautions", models.TextField(default="")),
                ("flowering", models.BooleanField(default=False)),
                ("size", models.CharField(default="", max_length=200)),
                ("image_front", models.TextField(default="")),
                ("render", models.TextField(default="")),
                ("created_at", models.DateField(auto_now_add=True)),
                ("inside", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PlantStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                ("price", models.BigIntegerField(default=0)),
                ("discount", models.IntegerField(default=0)),
                ("state", models.BooleanField(default=True)),
                (
                    "id_plant",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plants.plant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=210)),
                ("price", models.BigIntegerField()),
                ("image", models.TextField()),
                ("quantity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ProductEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("cost", models.BigIntegerField()),
                (
                    "id_plant",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plants.plantstock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gift", models.BooleanField(default=False)),
                (
                    "id_crystal",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plants.crystalstock",
                    ),
                ),
                (
                    "id_plant",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plants.plantstock",
                    ),
                ),
                (
                    "id_pot",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plants.pot",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductOrderToOrderSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_order_sale",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plants.ordersale",
                    ),
                ),
                (
                    "id_product_order",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plants.productorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductEntryToOrderPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_order_purchase",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plants.orderpurchase",
                    ),
                ),
                (
                    "id_product_entry",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plants.productentry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlantFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_plant",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plants.plantstock",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CrystalFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_crystal",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plants.crystalstock",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
