# Generated by Django 4.1.4 on 2022-12-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=210)),
                ("other_names", models.TextField(default="")),
                ("description", models.TextField()),
                ("species", models.CharField(max_length=200)),
                ("group", models.CharField(max_length=200)),
                ("light", models.TextField(default="")),
                ("irrigation", models.CharField(max_length=200)),
                ("temperature", models.CharField(max_length=200)),
                ("precautions", models.TextField(default="")),
                ("flowering", models.BooleanField()),
                ("size", models.CharField(max_length=200)),
                ("image_front", models.TextField()),
                ("render", models.TextField()),
                ("created_at", models.DateField(auto_now_add=True)),
                ("inside", models.BooleanField()),
            ],
        ),
    ]
