# Generated by Django 4.1.4 on 2022-12-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Crystal",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(default="")),
                ("vibration", models.IntegerField(default=0)),
                ("benefits", models.JSONField(default="")),
                ("properties", models.JSONField(default="")),
                ("zodiac", models.JSONField(default="")),
                ("planets", models.JSONField(default="")),
                ("elements", models.JSONField(default="")),
                ("chakras", models.JSONField(default="")),
                ("image_crystal", models.TextField(default="")),
                ("image_gemstone", models.TextField(default="")),
            ],
        ),
        migrations.AlterField(
            model_name="plant",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="plant",
            name="flowering",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="plant",
            name="image_front",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="plant",
            name="inside",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="plant",
            name="other_names",
            field=models.JSONField(default=""),
        ),
        migrations.AlterField(
            model_name="plant",
            name="precautions",
            field=models.JSONField(default=""),
        ),
        migrations.AlterField(
            model_name="plant",
            name="render",
            field=models.TextField(default=""),
        ),
    ]
