# Generated by Django 4.1.4 on 2023-06-10 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pot',
            name='render',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
    ]
