# Generated by Django 4.1.4 on 2023-08-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_pot_render'),
    ]

    operations = [
        migrations.AddField(
            model_name='pot',
            name='size',
            field=models.TextField(default=''),
        ),
    ]
