# Generated by Django 4.1.4 on 2022-12-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0002_crystal_alter_plant_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crystal",
            name="benefits",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="crystal",
            name="chakras",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="crystal",
            name="elements",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="crystal",
            name="planets",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="crystal",
            name="properties",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="crystal",
            name="zodiac",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="plant",
            name="other_names",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="plant",
            name="precautions",
            field=models.TextField(default=""),
        ),
    ]
