# Generated by Django 4.1.4 on 2023-08-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_pot_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='inside',
            field=models.TextField(default='inside'),
        ),
    ]
