# Generated by Django 4.1.4 on 2022-12-22 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0004_alter_crystal_id_alter_plant_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrystalStock",
            fields=[
                (
                    "id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="plants.crystal",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                ("price", models.BigIntegerField(default=0)),
                ("state", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlantStock",
            fields=[
                (
                    "id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="plants.plant",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                ("price", models.BigIntegerField(default=0)),
                ("discount", models.IntegerField(default=0)),
                ("state", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=210)),
                ("password", models.CharField(max_length=210)),
                ("roles", models.TextField(default="USER_ROLE")),
            ],
        ),
        migrations.CreateModel(
            name="PlantFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plants.plant"
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plants.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CystalFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_plant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plants.crystal"
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plants.user"
                    ),
                ),
            ],
        ),
    ]
