# Generated by Django 4.2.4 on 2023-08-20 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_alter_plant_inside'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='inside',
            new_name='zone',
        ),
    ]
