# Generated by Django 4.1.4 on 2022-12-22 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0005_crystalstock_plantstock_user_plantfavorite_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crystalstock",
            name="id_crystal",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="plants.crystal",
            ),
        ),
        migrations.AddField(
            model_name="plantstock",
            name="id_plant",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="plants.plant",
            ),
        ),
        migrations.AlterField(
            model_name="crystalstock",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="plantstock",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
