# Generated by Django 4.1.4 on 2022-12-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0006_crystalstock_id_crystal_plantstock_id_plant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crystal",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
