# Generated by Django 4.1.4 on 2022-12-23 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0008_remove_cystalfavorite_id_plant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantfavorite",
            name="id_plant",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="plants.plantstock",
            ),
        ),
        migrations.AlterField(
            model_name="plantfavorite",
            name="id_user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="plants.user",
            ),
        ),
    ]
