# Generated by Django 4.1.4 on 2022-12-31 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0009_alter_plantfavorite_id_plant_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_products", models.IntegerField()),
                ("total_cost", models.BigIntegerField()),
                ("order_at", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrderSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_products", models.IntegerField()),
                ("address", models.TextField()),
                ("payment_method", models.TextField()),
                ("payment_state", models.BooleanField()),
                ("order_at", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=210)),
                ("price", models.BigIntegerField()),
                ("image", models.TextField()),
                ("quantity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ProductEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("cost", models.BigIntegerField()),
                (
                    "id_plant",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plants.plantstock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gift", models.BooleanField(default=False)),
                (
                    "id_crystal",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plants.crystalstock",
                    ),
                ),
                (
                    "id_plant",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plants.plantstock",
                    ),
                ),
                (
                    "id_pot",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plants.pot",
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plants.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductOrderToOrderSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_order_sale",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plants.ordersale",
                    ),
                ),
                (
                    "id_product_order",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plants.productorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductEntryToOrderPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_order_purchase",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plants.orderpurchase",
                    ),
                ),
                (
                    "id_product_entry",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plants.productentry",
                    ),
                ),
            ],
        ),
    ]
