# Generated by Django 4.1.4 on 2023-01-03 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("plants", "0011_user_groups_user_image_user_is_superuser_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CystalFavorite",
            new_name="CrystalFavorite",
        ),
    ]
